### ISSUE TITLE
2 PRÁCTICA

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/practica-de-predicados-cuantificadores-eq-erick-yanet-lourdes-1as#1]
[PRÁCTICA DE PREDICADOS-CUANTIFICADORES.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-predicados-cuantificadores-eq-erick-yanet-lourdes-1as/files/7530777/PRACTICA.DE.PREDICADOS-CUANTIFICADORES.pdf)

**Comment by alexis663** [comment]
Portada(excelente): Si cuenta con los parametros requeridos. 25 puntos
Procedimiento(excelente): Describe correctamente su procedimiento de cada ejercicio. 25 puntos
Figuras, ilustraciones y fotografias: Cuenta con las figuras necesarias que se requieren. 25 puntos
Resultados y conclusiones(excelente): Si cubre lo requerido en la rúbrica. 25 puntos
Total: 100/100
Calificación: 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
